language: android
jdk: oraclejdk8

android:
  components:
    # use the latest revision of Android SDK Tools
    - tools
    - platform-tools
    # The BuildTools version used by your project
    - build-tools-25.0.3
    # The SDK version used to compile your project
    - android-25
    # Additional components
    - extra-google-m2repository
    - extra-android-m2repository
  licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'  

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    
before_script:
  # Create and start emulator


script: ./gradlew assembleRelease
