language: android
jdk: oraclejdk8

android:
  components:
    # use the latest revision of Android SDK Tools
    # - tools
    # - platform-tools

    # The BuildTools version used by your project
    - build-tools-25.0.3
    # The SDK version used to compile your project
    - android-25
    # Additional components
  
    
before_script:
  # Create and start emulator


script: ./gradlew assembleRelease
